# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY generate_threats.py .

# Install Scapy
RUN pip install scapy numpy

# Run generate_threats.py when the container launches
CMD ["python", "generate_threats.py"]
